language: node_js

node_js: 
  - "stable"

services:
  - docker

script:
  - echo "npm test"  


before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in iaas-ccm1-302108-a04c21265507.json.enc -out iaas-ccm1-302108-a04c21265507.json -d

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
      