language: node_js

node_js: 
  - "stable"

services:
  - docker

script:
  - echo "npm test"  

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
      